- name: Apply Calico CNI Plugin
  hosts: master
  become: yes
  tasks:
    - name: Apply Calico manifest
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml